### ISSUE TITLE
landscape mode UI cuts off right side of keyboard in Android-15

### ISSUE THREAD

**Issue by netllama** [klausw/hackerskeyboard#957]
**Describe the bug**
Landscape mode UI is cut off on the right side in Android 15 (did not happen in Android 14).  Happening on a Pixel 8 phone.

**To Reproduce**
Attempt to use keyboard in landscape orientation

**Expected behavior**
UI isn't cut off

**Screenshots**
![Screenshot_20241208-181925](https://github.com/user-attachments/assets/5f615f59-e9f4-40c6-888c-73e6a49fb07b)

**Smartphone (please complete the following information):**
 - Device: Pixel8
 - OS: Android 15
 - App version 1.41.1

**Comment by ghost** [comment]
I'm working on it, this is the progress so far

![Image](https://github.com/user-attachments/assets/d6f6023e-1735-4dd7-8366-27af70d44e52)

**Comment by netllama** [comment]
@mcagabe19 thanks for the update.  that looks way way better.  do you have a pkg available with that change that I could test out?

**Comment by r0d0dendr0n** [comment]
On latest lineageos for poco f6 pro the behaviour is the same. Thank you for your work!

**Comment by ghost** [comment]
the issue is I can't fix the button size, idk how can I fix this..

**Comment by ghost** [comment]
can someone help if it's possible?

https://github.com/mcagabe19/hackerskeyboard

**Comment by ruslan-k13** [comment]
It's a good keyboard for Termix sessions. However, after updating to Android 15, landscape mode broke: part of the keyboard is covered by the navigation bar on the right. The bar cannot be hidden either (as I had it before, in the 14th Android).

I've tried using transparent navigation bar, and gestures instead of the preferred 3 buttons navigation. Doesn't help. Attached are screenshots of 3 buttons, gestures, and transparent 3 buttons navigation modes. Note that in the gestures mode the keyboard is still trancated.

![Image](https://github.com/user-attachments/assets/c1befcd8-7350-4523-b905-636b1e721ef4)

![Image](https://github.com/user-attachments/assets/a70cdd2e-844a-43af-a4f0-d52c86554442)

![Image](https://github.com/user-attachments/assets/e9aac4ad-6f33-4cdd-8dd5-815b58c4cf9a)

Used on Pixel 6a
Android 15
Keyboard v. 1.40.7

UPDATE.
After posting screenshots here, I've noticed that they all have black indentation on the left. I understand what's going on now. In the indented are Pixel 6a has front facing webcam. In Android 14 I remember that camera was in the middle of the text window, and the text window was the same width as the screen window, so the keyboard fit well. Now, in Android 15, they shrank text window, so the camera will be outside of it. So, it became smaller than the screen window. And since the keyboard, apparently, uses screen window to calculate its size, it won't fit into the text window anymore.

I would recommend, in addition to using proper window width for "auto" calculations, provide a fallback setting for the manual width of a landscape mode layout.

**Comment by ruslan-k13** [comment]
I think the width is set to wide in here, should be reduced a bit.

https://github.com/klausw/hackerskeyboard/blob/9202d9d8b1d379f1a20edf08ed7e7149038c8e43/app/src/main/java/org/pocketworkstation/pckeyboard/Keyboard.java#L830

**Comment by ghost** [comment]
mkay I'll look when I got time

**Comment by ByWindy** [comment]
> **Describe the bug**
> Landscape mode UI is cut off on the right side in Android 15 (did not happen in Android 14).  Happening on a Pixel 8 phone.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> Attempt to use keyboard in landscape orientation
> 
> **Expected behavior**
> UI isn't cut off
> 
> **Screenshots**
> ![Screenshot_20241208-181925](https://github.com/user-attachments/assets/5f615f59-e9f4-40c6-888c-73e6a49fb07b)
> 
> **Smartphone (please complete the following information):**
>  - Device: Pixel8
>  - OS: Android 15
>  - App version 1.41.1
> 
>

**Comment by abugher** [comment]
Observing same on Pixel 4a, Android 15, app version 1.40.7.

**Comment by ruslan-k13** [comment]
![Image](https://github.com/user-attachments/assets/1a694b67-255a-4359-a245-e5d7591b5f53)

The issue seems to be fixed now.
Thank you.

Used on Pixel 6a
Android 15, build BP1A.250405.007
Keyboard v. 1.41.1

**Comment by netllama** [comment]
@ruslan-k13   I don't understand.  What changed that fixed this for you?   Its very much still broken for me on Android15.

**Comment by ruslan-k13** [comment]
@netllama  I've restarted my phone yesterday, to finish an update that was waiting there for few weeks already. The keyboard was fixed after the reboot. I looked at the keyboard app version, and noticed it is 1.41.1 (my broken one was 1.40.7). So , I assumed that it was the keyboard update that fixed the issue...

It is possible, though, that it was the Android update that fixed it. Check out your build number. If it is smaller than the one I've mentioned in my "thank you" comment, I would advise to upgrade your Android OS. It won't hurt, and can help...

**Comment by ruslan-k13** [comment]
I've noticed one "special feature", though. If you keep switching your keyboard layouts in the landscape mode, then hackers keyboard still appears broken each and every time. But a quick flick to the portrait and back fixes the landscape layout. If you start with portrait and rotate to landscape - it will look alright. I think I can live with that.

**Comment by abugher** [comment]
* Device:  Pixel 4a (sunfish)
* App version:  1.40.7
* Android version:  15
* Android build:  BP1A.250405.007 4008c41278

I think the bug is fixed for me.  I seem to have a visible and working backspace key in landscape mode, now.  I have not observed the same "special feature" described by @ruslan-k13; the full keyboard remained visible in landscape mode after changing keyboard layout.

I updated my OS but not the app since my last post.

**Comment by S34NN** [comment]
Glad to hear it was fixed for some, likely with an Android update. Unfortunately no such luck with Samsung's flavor of Android 15 in OneUI 7.0. I don't expect much in the way of updates from them either since the OneUI 8 beta is rumored to start rolling out in June.

**Comment by ruslan-k13** [comment]
Somewhere above I've advised a fallback setting for changing the width manually in the landscape mode (same as you can do it with the height). I understand that fixing it properly for different buggy Android implementations might be tricky. But this should be an easy and robust hack (pun intended :) ) around the problem. The "auto" width might remain or get again broken in future updates, but the ability of setting up the width manually will alleviate the problem.

**Comment by bjorklund** [comment]
The problem still exist for Samsung devices. Problem came in UI 7.

**Comment by kyberneticist** [comment]
Tested the 1.41.1 apk - issue still exists in samsung devices. I agree with ruslan that abillity to control width would be a good workaround.  Or specify a right padding width.

**Comment by r0d0dendr0n** [comment]
> Tested the 1.41.1 apk - issue still exists in samsung devices. I agree with ruslan that abillity to control width would be a good workaround. Or specify a right padding width.

You might notice the apk is almost 7 years old and is much older than this bug report.

**Comment by klausw** [comment]
Sorry, the application is unfortunately obsolete at this point. It was written in 2011 and is based on the Android 2.3 (Gingerbread) AOSP keyboard. I can no longer update it via Google Play since app updates require a minimum API level of 34, while the code was written for API level 9. It would need major rework to function with current Android APIs, and I don't have plans at this point to do so.

**Comment by r0d0dendr0n** [comment]
@klausw f-droid maybe?

**Comment by kyberneticist** [comment]
> > Tested the 1.41.1 apk - issue still exists in samsung devices. I agree with ruslan that abillity to control width would be a good workaround. Or specify a right padding width.
> 
> You might notice the apk is almost 7 years old and is much older than this bug report.

Oops. Was reading the thread while running a fever, didn't notice the work mentioned was in a fork, thought it was the alpha - didn't even check dates. Thanks for pointing it out.

**Comment by kyberneticist** [comment]
> Sorry, the application is unfortunately obsolete at this point. It was written in 2011 and is based on the Android 2.3 (Gingerbread) AOSP keyboard. I can no longer update it via Google Play since app updates require a minimum API level of 34, while the code was written for API level 9. It would need major rework to function with current Android APIs, and I don't have plans at this point to do so.

Well.  I really appreciated it during the past decade+ of use.  Loved the compose function, long touch for accents/alternate keys, attractive layout... Haven't found an alternative out there.  CodeBoard is the closest, although it has same bug at present, and does not have the same feature set (and hacker's keyboard has a prettier layout IMO, but may just be what I'm used to)

**Comment by bjorklund** [comment]
I agree, there is nothing like hackers keyboard. :-(

**Comment by kyberneticist** [comment]
Basic workaround until I get around to figuring out how to build this project and cram in an option to add a bit of padding on the right hand side in landscape mode.  At least on my Samsung phone you can replace the nav bar with gestures.  Positive, keyboard no longer obscured.  Negative, gestures occasionally screw up apps by grabbing the edge of the screen.  But it's pretty easy to switch back and forth.

**Comment by S34NN** [comment]
> Basic workaround until I get around to figuring out how to build this project and cram in an option to add a bit of padding on the right hand side in landscape mode. At least on my Samsung phone you can replace the nav bar with gestures. Positive, keyboard no longer obscured. Negative, gestures occasionally screw up apps by grabbing the edge of the screen. But it's pretty easy to switch back and forth.

I use the same workaround for now on my S24U. To make it a bit more convenient I created a quick settings tile to trigger an activity to open the navigation bar section in Android settings to be able to switch between buttons or gestures. If interested, the activity name is:

com.android.settings.Settings$NavigationBarSettingsActivity

I also enabled the NavStar plugin in Good Lock to turn on additional gesture settings so I can use the option for seperate gesture areas for recent apps, home, and back rather than the single combined gesture area.

I was also testing with Tasker + Shizuku to enable automatic keyboard switching on a per app basis so that it sets Hacker's Keyboard as the active keyboard which works fine. I was hoping it might be possible to also automate switching between buttons/gesture navigation, but I haven't had success yet with figuring out if that is even possible to trigger with Tasker integration with Shizuku.

**Comment by kyberneticist** [comment]
Thanks for the tips.  I really do need to get around to doing a build of this project.  A couple of other (lame) workarounds I've found is that since I'm usually just missing the |  key when typing in a terminal, I added the german keyboard so I can swipe left to get to it, then get the pipe key which is under one of the main german keys.  Also the backspace at least on my phone is accessible from under Fn  in landscape mode.

Reducing the size of the nav bar using the samsung navstar tool exposes the backspace in normal insert mode, and makes the Enter/Ok a bit more visible, but does not get the | symbol.  And unfortunately the "hide navbar" button in navstar only works in situations the app would be able to do that anyway.

... correction.. you can just barely touch the pipe symbol with the medium size navbar from navstar, and it gets a bit easier with the smallest one.

**Comment by AlainKnaff** [comment]
Found the reason for the bug. In class org.pocketworkstation.pckeyboard.LatinKeyboardBaseView method onMeasure(), it ignores any size (width) updates that are smaller than the provisional width at creation. In Android >= 15, Sdk level >= 35, the screen dimensions on which that provisional width is based include unusable space occupied by camera and navigation bar. If updates to the width (which are based on actual layout computations) are ignored, the keyboard will be too wide, and not fit in the space allocated by the layout manager.

Commit [0dd9cd7](https://github.com/klausw/hackerskeyboard/pull/978/commits/0dd9cd789cd098b5532d864249106e1504553da0) from my pull request 978 fixes this.

**Comment by r0d0dendr0n** [comment]
Version 1.40.7 works properly on Lineage 23.2 (Android 16).

**Comment by codenameberyl** [comment]
hi, try my version here: [https://github.com/codenameberyl/hackerkeyboard/releases](https://github.com/codenameberyl/hackerkeyboard/releases). Also added emojis, clipboard with pinning. Let me know what you think.
